/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import gestionFichiers.lecteur;
import gestioncompetences.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Entrax
 */
public class DetailsMissionEnCours extends javax.swing.JFrame {

    private static String libelle, dateDebut, duree, etat;
    private final MissionEnCours mission;

    private HashMap<Competence, ArrayList<Personne>> affectationsCompetencesMission = new HashMap<>();
    private HashMap<String, HashMap<String, ArrayList<Integer>>> affectationsMission = new HashMap<>();

    /**
     * Creates new form DetailsMissionPreparation
     *
     * @param libelle
     * @param dateDebut
     * @param duree
     * @param etat
     * @throws java.io.IOException
     */
    public DetailsMissionEnCours(String libelle, String dateDebut, String duree, String etat) throws IOException {
        initComponents();
        DetailsMissionEnCours.libelle = libelle;
        DetailsMissionEnCours.dateDebut = dateDebut;
        DetailsMissionEnCours.duree = duree;
        DetailsMissionEnCours.etat = etat;
        jLabelLibelleMission.setText(libelle);

        MissionEnCours m = MissionEnCours.getMissionByLibelle(libelle);
        if (m == null) {
            HashMap<Competence, ArrayList<Personne>> personelRequis = new HashMap<>();
            this.mission = new MissionEnCours(libelle, dateDebut, duree, etat, personelRequis);
        } else {
            this.mission = new MissionEnCours(m.getLibelle(), m.getDateDebut(), m.getDuree(), m.getEtat(), m.getAffectationDefinitive());
        }

        affectationsMission = lecteur.getAffectationsParMission(lecteur.cheminAffectationsMission);
        HashMap<String, ArrayList<Integer>> libCompetences = affectationsMission.get(this.mission.getLibelle());
        if (libCompetences != null) {
            for (String competenceMission : libCompetences.keySet()) {
                try {
                    Competence competence;
                    competence = Competence.getCompetenceById(competenceMission);
                    ArrayList<Personne> personnes = new ArrayList<>();
                    for (int idPersonne : libCompetences.get(competenceMission)) {
                        personnes.add(Personne.getPersonneById(idPersonne));
                    }
                    affectationsCompetencesMission.put(competence, personnes);
                } catch (IOException ex) {
                    Logger.getLogger(MissionPlanifiee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        for (Competence cp : affectationsCompetencesMission.keySet()) {
            int nb = 0;
            if (affectationsCompetencesMission.get(cp) != null) {
                nb = affectationsCompetencesMission.get(cp).size();
            }
            tableCompetencesMissionModel.addRow(new Object[]{cp.getIdCompetence(), cp.getNomEN(), cp.getNomFR(), nb});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLibelleMission = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCompetencesMissionModel = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Identifiant", "Libellé EN", "Libellé FR", "Personnel assigné"
            })
            {
                @Override
                public boolean isCellEditable(int row, int column)
                {
                    return false;
                }
            };
            jTableCompetencesMission = new javax.swing.JTable();
            jButtonTerminer = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            tablePersonnesCompetenceMissionModel = new DefaultTableModel(              new Object [][] {},              new String [] {                  "Identifiant", "Nom", "Prénom", "Date d'entrée"              })
            {
                @Override
                public boolean isCellEditable(int row, int column)
                {
                    return false;
                }
            };
            jTablePersonnesCompetenceMission = new javax.swing.JTable();
            jLabel1 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Détails Mission Planifiee");

            jTableCompetencesMission.setAutoCreateRowSorter(true);
            jTableCompetencesMission.setModel(tableCompetencesMissionModel);
            jTableCompetencesMission.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTableCompetencesMissionMouseClicked(evt);
                }
            });
            jScrollPane2.setViewportView(jTableCompetencesMission);

            jButtonTerminer.setText("Terminer");
            jButtonTerminer.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButtonTerminerMouseClicked(evt);
                }
            });

            jTablePersonnesCompetenceMission.setAutoCreateRowSorter(true);
            jTablePersonnesCompetenceMission.setModel(tablePersonnesCompetenceMissionModel);
            jScrollPane1.setViewportView(jTablePersonnesCompetenceMission);

            jLabel1.setText("Affectations");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelLibelleMission)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTerminer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonTerminer)
                        .addComponent(jLabelLibelleMission))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addGap(40, 40, 40))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTableCompetencesMissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCompetencesMissionMouseClicked
        // TODO add your handling code here:

        String idComp = tableCompetencesMissionModel.getValueAt(jTableCompetencesMission.getSelectedRow(), 0).toString();
        //Affichage du personnel de la mission
        while (tablePersonnesCompetenceMissionModel.getRowCount() != 0) {
            tablePersonnesCompetenceMissionModel.removeRow(0);
        }
        Competence cp;
        ArrayList<Personne> personnel = new ArrayList<>();
        try {
            cp = Competence.getCompetenceById(idComp);
            for (Competence comp : affectationsCompetencesMission.keySet()) {
                if (comp.getIdCompetence().equals(cp.getIdCompetence())) {
                    personnel = affectationsCompetencesMission.get(comp);
                }
            }
            for (Personne pers : personnel) {
                tablePersonnesCompetenceMissionModel.addRow(new Object[]{pers.getId(), pers.getNom(), pers.getPrenom(), pers.getDateEntree()});
            }
        } catch (IOException ex) {
            Logger.getLogger(DetailsMissionEnCours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableCompetencesMissionMouseClicked

    private void jButtonTerminerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTerminerMouseClicked
        // TODO add your handling code here:
        this.mission.prochainEtat();

        this.dispose();
    }//GEN-LAST:event_jButtonTerminerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsMissionEnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsMissionEnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsMissionEnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsMissionEnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DetailsMissionEnCours(DetailsMissionEnCours.libelle, DetailsMissionEnCours.dateDebut, DetailsMissionEnCours.duree, DetailsMissionEnCours.etat).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(DetailsMissionEnCours.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTerminer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLibelleMission;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCompetencesMission;
    private javax.swing.JTable jTablePersonnesCompetenceMission;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel tableCompetencesMissionModel;
    DefaultTableModel tablePersonnesCompetenceMissionModel;
}
